<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="coordinator" nsURI="http://udem.iro.geodes.ca/coordinator" nsPrefix="coordinator">
  <eClassifiers xsi:type="ecore:EClass" name="CoordinatorDiagram"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupNode"/>
</ecore:EPackage>
