/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.ui;

import ca.udem.iro.geodes.interaction.ui.AbstractInteractiontxtUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class InteractiontxtUiModule extends AbstractInteractiontxtUiModule {
  public InteractiontxtUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
