/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class InteractiontxtQuickfixProvider extends DefaultQuickfixProvider {
}
