/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.interactiontxt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ACanvas</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.udem.iro.geodes.interaction.interactiontxt.ACanvas#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see ca.udem.iro.geodes.interaction.interactiontxt.InteractiontxtPackage#getACanvas()
 * @model
 * @generated
 */
public interface ACanvas extends AElement
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see ca.udem.iro.geodes.interaction.interactiontxt.InteractiontxtPackage#getACanvas_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link ca.udem.iro.geodes.interaction.interactiontxt.ACanvas#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // ACanvas
