/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.interactiontxt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AElement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.udem.iro.geodes.interaction.interactiontxt.InteractiontxtPackage#getAElement()
 * @model
 * @generated
 */
public interface AElement extends CAElement
{
} // AElement
