/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.interactiontxt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CA Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.udem.iro.geodes.interaction.interactiontxt.InteractiontxtPackage#getCAElement()
 * @model
 * @generated
 */
public interface CAElement extends EObject
{
} // CAElement
