/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.interactiontxt;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ca.udem.iro.geodes.interaction.interactiontxt.InteractiontxtFactory
 * @model kind="package"
 * @generated
 */
public interface InteractiontxtPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "interactiontxt";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.udem.ca/iro/geodes/interaction/Interactiontxt";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "interactiontxt";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  InteractiontxtPackage eINSTANCE = ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl.init();

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ModelImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Interactions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__INTERACTIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CAElementImpl <em>CA Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CAElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCAElement()
   * @generated
   */
  int CA_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>CA Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CA_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CElementImpl <em>CElement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCElement()
   * @generated
   */
  int CELEMENT = 2;

  /**
   * The feature id for the '<em><b>Is Negative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELEMENT__IS_NEGATIVE = CA_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Is Focus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELEMENT__IS_FOCUS = CA_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELEMENT__VALUE = CA_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>CElement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELEMENT_FEATURE_COUNT = CA_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.AElementImpl <em>AElement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.AElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAElement()
   * @generated
   */
  int AELEMENT = 3;

  /**
   * The number of structural features of the '<em>AElement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AELEMENT_FEATURE_COUNT = CA_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractionImpl <em>Interaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractionImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getInteraction()
   * @generated
   */
  int INTERACTION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__CONDITION = 1;

  /**
   * The number of structural features of the '<em>Interaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ConditionImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__ID = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__ELEMENTS = 1;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__TRANSITION = 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.StartTransitionImpl <em>Start Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.StartTransitionImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getStartTransition()
   * @generated
   */
  int START_TRANSITION = 6;

  /**
   * The feature id for the '<em><b>Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_TRANSITION__EVENT = 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_TRANSITION__ACTION = 1;

  /**
   * The number of structural features of the '<em>Start Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_TRANSITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.TransitionImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 7;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__ACTION = 0;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ActionImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAction()
   * @generated
   */
  int ACTION = 8;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ID = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ELEMENTS = 1;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__TRANSITION = 2;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CIElementImpl <em>CI Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CIElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCIElement()
   * @generated
   */
  int CI_ELEMENT = 9;

  /**
   * The feature id for the '<em><b>Is Negative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CI_ELEMENT__IS_NEGATIVE = CELEMENT__IS_NEGATIVE;

  /**
   * The feature id for the '<em><b>Is Focus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CI_ELEMENT__IS_FOCUS = CELEMENT__IS_FOCUS;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CI_ELEMENT__VALUE = CELEMENT__VALUE;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CI_ELEMENT__ID = CELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CI_ELEMENT__OPERATION = CELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>CI Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CI_ELEMENT_FEATURE_COUNT = CELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CLElementImpl <em>CL Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CLElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCLElement()
   * @generated
   */
  int CL_ELEMENT = 10;

  /**
   * The feature id for the '<em><b>Is Negative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CL_ELEMENT__IS_NEGATIVE = CELEMENT__IS_NEGATIVE;

  /**
   * The feature id for the '<em><b>Is Focus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CL_ELEMENT__IS_FOCUS = CELEMENT__IS_FOCUS;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CL_ELEMENT__VALUE = CELEMENT__VALUE;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CL_ELEMENT__ID = CELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CL_ELEMENT__OPERATION = CELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>CL Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CL_ELEMENT_FEATURE_COUNT = CELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CCanvasImpl <em>CCanvas</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CCanvasImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCCanvas()
   * @generated
   */
  int CCANVAS = 11;

  /**
   * The feature id for the '<em><b>Is Negative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CCANVAS__IS_NEGATIVE = CELEMENT__IS_NEGATIVE;

  /**
   * The feature id for the '<em><b>Is Focus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CCANVAS__IS_FOCUS = CELEMENT__IS_FOCUS;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CCANVAS__VALUE = CELEMENT__VALUE;

  /**
   * The number of structural features of the '<em>CCanvas</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CCANVAS_FEATURE_COUNT = CELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CVElementImpl <em>CV Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CVElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCVElement()
   * @generated
   */
  int CV_ELEMENT = 12;

  /**
   * The feature id for the '<em><b>Is Negative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CV_ELEMENT__IS_NEGATIVE = CELEMENT__IS_NEGATIVE;

  /**
   * The feature id for the '<em><b>Is Focus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CV_ELEMENT__IS_FOCUS = CELEMENT__IS_FOCUS;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CV_ELEMENT__VALUE = CELEMENT__VALUE;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CV_ELEMENT__ID = CELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CV_ELEMENT__ELEMENT = CELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>CV Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CV_ELEMENT_FEATURE_COUNT = CELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.AIElementImpl <em>AI Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.AIElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAIElement()
   * @generated
   */
  int AI_ELEMENT = 13;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AI_ELEMENT__ID = AELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AI_ELEMENT__VALUE = AELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>AI Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AI_ELEMENT_FEATURE_COUNT = AELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.AOElementImpl <em>AO Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.AOElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAOElement()
   * @generated
   */
  int AO_ELEMENT = 14;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AO_ELEMENT__OPERATION = AELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AO_ELEMENT__VALUE = AELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>AO Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AO_ELEMENT_FEATURE_COUNT = AELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ALElementImpl <em>AL Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ALElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getALElement()
   * @generated
   */
  int AL_ELEMENT = 15;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AL_ELEMENT__ID = AELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AL_ELEMENT__OPERATION = AELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AL_ELEMENT__VALUE = AELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>AL Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AL_ELEMENT_FEATURE_COUNT = AELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ACanvasImpl <em>ACanvas</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ACanvasImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getACanvas()
   * @generated
   */
  int ACANVAS = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACANVAS__VALUE = AELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>ACanvas</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACANVAS_FEATURE_COUNT = AELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.AVElementImpl <em>AV Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.AVElementImpl
   * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAVElement()
   * @generated
   */
  int AV_ELEMENT = 17;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ELEMENT__ID = AELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ELEMENT__OPERATION = AELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ELEMENT__VALUE = AELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ELEMENT__ELEMENT = AELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>AV Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AV_ELEMENT_FEATURE_COUNT = AELEMENT_FEATURE_COUNT + 4;


  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link ca.udem.iro.geodes.interaction.interactiontxt.Model#getInteractions <em>Interactions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Interactions</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Model#getInteractions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Interactions();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.CAElement <em>CA Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CA Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CAElement
   * @generated
   */
  EClass getCAElement();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.CElement <em>CElement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CElement</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CElement
   * @generated
   */
  EClass getCElement();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.CElement#isIsNegative <em>Is Negative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Negative</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CElement#isIsNegative()
   * @see #getCElement()
   * @generated
   */
  EAttribute getCElement_IsNegative();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.CElement#isIsFocus <em>Is Focus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Focus</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CElement#isIsFocus()
   * @see #getCElement()
   * @generated
   */
  EAttribute getCElement_IsFocus();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.CElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CElement#getValue()
   * @see #getCElement()
   * @generated
   */
  EAttribute getCElement_Value();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.AElement <em>AElement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AElement</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AElement
   * @generated
   */
  EClass getAElement();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.Interaction <em>Interaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interaction</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Interaction
   * @generated
   */
  EClass getInteraction();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.Interaction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Interaction#getName()
   * @see #getInteraction()
   * @generated
   */
  EAttribute getInteraction_Name();

  /**
   * Returns the meta object for the containment reference '{@link ca.udem.iro.geodes.interaction.interactiontxt.Interaction#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Interaction#getCondition()
   * @see #getInteraction()
   * @generated
   */
  EReference getInteraction_Condition();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.Condition#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Condition#getId()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Id();

  /**
   * Returns the meta object for the containment reference list '{@link ca.udem.iro.geodes.interaction.interactiontxt.Condition#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Condition#getElements()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Elements();

  /**
   * Returns the meta object for the containment reference '{@link ca.udem.iro.geodes.interaction.interactiontxt.Condition#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transition</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Condition#getTransition()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Transition();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.StartTransition <em>Start Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Start Transition</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.StartTransition
   * @generated
   */
  EClass getStartTransition();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.StartTransition#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Event</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.StartTransition#getEvent()
   * @see #getStartTransition()
   * @generated
   */
  EAttribute getStartTransition_Event();

  /**
   * Returns the meta object for the containment reference list '{@link ca.udem.iro.geodes.interaction.interactiontxt.StartTransition#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.StartTransition#getAction()
   * @see #getStartTransition()
   * @generated
   */
  EReference getStartTransition_Action();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the containment reference list '{@link ca.udem.iro.geodes.interaction.interactiontxt.Transition#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Transition#getAction()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Action();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.Action#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Action#getId()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Id();

  /**
   * Returns the meta object for the containment reference list '{@link ca.udem.iro.geodes.interaction.interactiontxt.Action#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Action#getElements()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Elements();

  /**
   * Returns the meta object for the containment reference '{@link ca.udem.iro.geodes.interaction.interactiontxt.Action#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transition</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.Action#getTransition()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Transition();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.CIElement <em>CI Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CI Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CIElement
   * @generated
   */
  EClass getCIElement();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.CIElement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CIElement#getId()
   * @see #getCIElement()
   * @generated
   */
  EAttribute getCIElement_Id();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.CIElement#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CIElement#getOperation()
   * @see #getCIElement()
   * @generated
   */
  EAttribute getCIElement_Operation();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.CLElement <em>CL Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CL Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CLElement
   * @generated
   */
  EClass getCLElement();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.CLElement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CLElement#getId()
   * @see #getCLElement()
   * @generated
   */
  EAttribute getCLElement_Id();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.CLElement#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CLElement#getOperation()
   * @see #getCLElement()
   * @generated
   */
  EAttribute getCLElement_Operation();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.CCanvas <em>CCanvas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CCanvas</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CCanvas
   * @generated
   */
  EClass getCCanvas();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.CVElement <em>CV Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CV Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CVElement
   * @generated
   */
  EClass getCVElement();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.CVElement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CVElement#getId()
   * @see #getCVElement()
   * @generated
   */
  EAttribute getCVElement_Id();

  /**
   * Returns the meta object for the reference '{@link ca.udem.iro.geodes.interaction.interactiontxt.CVElement#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.CVElement#getElement()
   * @see #getCVElement()
   * @generated
   */
  EReference getCVElement_Element();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.AIElement <em>AI Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AI Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AIElement
   * @generated
   */
  EClass getAIElement();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.AIElement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AIElement#getId()
   * @see #getAIElement()
   * @generated
   */
  EAttribute getAIElement_Id();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.AIElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AIElement#getValue()
   * @see #getAIElement()
   * @generated
   */
  EAttribute getAIElement_Value();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.AOElement <em>AO Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AO Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AOElement
   * @generated
   */
  EClass getAOElement();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.AOElement#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AOElement#getOperation()
   * @see #getAOElement()
   * @generated
   */
  EAttribute getAOElement_Operation();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.AOElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AOElement#getValue()
   * @see #getAOElement()
   * @generated
   */
  EAttribute getAOElement_Value();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.ALElement <em>AL Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AL Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.ALElement
   * @generated
   */
  EClass getALElement();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.ALElement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.ALElement#getId()
   * @see #getALElement()
   * @generated
   */
  EAttribute getALElement_Id();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.ALElement#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.ALElement#getOperation()
   * @see #getALElement()
   * @generated
   */
  EAttribute getALElement_Operation();

  /**
   * Returns the meta object for the attribute list '{@link ca.udem.iro.geodes.interaction.interactiontxt.ALElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.ALElement#getValue()
   * @see #getALElement()
   * @generated
   */
  EAttribute getALElement_Value();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.ACanvas <em>ACanvas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ACanvas</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.ACanvas
   * @generated
   */
  EClass getACanvas();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.ACanvas#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.ACanvas#getValue()
   * @see #getACanvas()
   * @generated
   */
  EAttribute getACanvas_Value();

  /**
   * Returns the meta object for class '{@link ca.udem.iro.geodes.interaction.interactiontxt.AVElement <em>AV Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AV Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AVElement
   * @generated
   */
  EClass getAVElement();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.AVElement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AVElement#getId()
   * @see #getAVElement()
   * @generated
   */
  EAttribute getAVElement_Id();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.AVElement#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AVElement#getOperation()
   * @see #getAVElement()
   * @generated
   */
  EAttribute getAVElement_Operation();

  /**
   * Returns the meta object for the attribute '{@link ca.udem.iro.geodes.interaction.interactiontxt.AVElement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AVElement#getValue()
   * @see #getAVElement()
   * @generated
   */
  EAttribute getAVElement_Value();

  /**
   * Returns the meta object for the reference '{@link ca.udem.iro.geodes.interaction.interactiontxt.AVElement#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Element</em>'.
   * @see ca.udem.iro.geodes.interaction.interactiontxt.AVElement#getElement()
   * @see #getAVElement()
   * @generated
   */
  EReference getAVElement_Element();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  InteractiontxtFactory getInteractiontxtFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ModelImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Interactions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__INTERACTIONS = eINSTANCE.getModel_Interactions();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CAElementImpl <em>CA Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CAElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCAElement()
     * @generated
     */
    EClass CA_ELEMENT = eINSTANCE.getCAElement();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CElementImpl <em>CElement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCElement()
     * @generated
     */
    EClass CELEMENT = eINSTANCE.getCElement();

    /**
     * The meta object literal for the '<em><b>Is Negative</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELEMENT__IS_NEGATIVE = eINSTANCE.getCElement_IsNegative();

    /**
     * The meta object literal for the '<em><b>Is Focus</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELEMENT__IS_FOCUS = eINSTANCE.getCElement_IsFocus();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELEMENT__VALUE = eINSTANCE.getCElement_Value();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.AElementImpl <em>AElement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.AElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAElement()
     * @generated
     */
    EClass AELEMENT = eINSTANCE.getAElement();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractionImpl <em>Interaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractionImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getInteraction()
     * @generated
     */
    EClass INTERACTION = eINSTANCE.getInteraction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION__NAME = eINSTANCE.getInteraction_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION__CONDITION = eINSTANCE.getInteraction_Condition();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ConditionImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__ID = eINSTANCE.getCondition_Id();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__ELEMENTS = eINSTANCE.getCondition_Elements();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__TRANSITION = eINSTANCE.getCondition_Transition();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.StartTransitionImpl <em>Start Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.StartTransitionImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getStartTransition()
     * @generated
     */
    EClass START_TRANSITION = eINSTANCE.getStartTransition();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute START_TRANSITION__EVENT = eINSTANCE.getStartTransition_Event();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START_TRANSITION__ACTION = eINSTANCE.getStartTransition_Action();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.TransitionImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__ACTION = eINSTANCE.getTransition_Action();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ActionImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__ID = eINSTANCE.getAction_Id();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__ELEMENTS = eINSTANCE.getAction_Elements();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__TRANSITION = eINSTANCE.getAction_Transition();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CIElementImpl <em>CI Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CIElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCIElement()
     * @generated
     */
    EClass CI_ELEMENT = eINSTANCE.getCIElement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CI_ELEMENT__ID = eINSTANCE.getCIElement_Id();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CI_ELEMENT__OPERATION = eINSTANCE.getCIElement_Operation();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CLElementImpl <em>CL Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CLElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCLElement()
     * @generated
     */
    EClass CL_ELEMENT = eINSTANCE.getCLElement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CL_ELEMENT__ID = eINSTANCE.getCLElement_Id();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CL_ELEMENT__OPERATION = eINSTANCE.getCLElement_Operation();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CCanvasImpl <em>CCanvas</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CCanvasImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCCanvas()
     * @generated
     */
    EClass CCANVAS = eINSTANCE.getCCanvas();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.CVElementImpl <em>CV Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.CVElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getCVElement()
     * @generated
     */
    EClass CV_ELEMENT = eINSTANCE.getCVElement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CV_ELEMENT__ID = eINSTANCE.getCVElement_Id();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CV_ELEMENT__ELEMENT = eINSTANCE.getCVElement_Element();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.AIElementImpl <em>AI Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.AIElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAIElement()
     * @generated
     */
    EClass AI_ELEMENT = eINSTANCE.getAIElement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AI_ELEMENT__ID = eINSTANCE.getAIElement_Id();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AI_ELEMENT__VALUE = eINSTANCE.getAIElement_Value();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.AOElementImpl <em>AO Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.AOElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAOElement()
     * @generated
     */
    EClass AO_ELEMENT = eINSTANCE.getAOElement();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AO_ELEMENT__OPERATION = eINSTANCE.getAOElement_Operation();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AO_ELEMENT__VALUE = eINSTANCE.getAOElement_Value();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ALElementImpl <em>AL Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ALElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getALElement()
     * @generated
     */
    EClass AL_ELEMENT = eINSTANCE.getALElement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AL_ELEMENT__ID = eINSTANCE.getALElement_Id();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AL_ELEMENT__OPERATION = eINSTANCE.getALElement_Operation();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AL_ELEMENT__VALUE = eINSTANCE.getALElement_Value();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.ACanvasImpl <em>ACanvas</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.ACanvasImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getACanvas()
     * @generated
     */
    EClass ACANVAS = eINSTANCE.getACanvas();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACANVAS__VALUE = eINSTANCE.getACanvas_Value();

    /**
     * The meta object literal for the '{@link ca.udem.iro.geodes.interaction.interactiontxt.impl.AVElementImpl <em>AV Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.AVElementImpl
     * @see ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtPackageImpl#getAVElement()
     * @generated
     */
    EClass AV_ELEMENT = eINSTANCE.getAVElement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AV_ELEMENT__ID = eINSTANCE.getAVElement_Id();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AV_ELEMENT__OPERATION = eINSTANCE.getAVElement_Operation();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AV_ELEMENT__VALUE = eINSTANCE.getAVElement_Value();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AV_ELEMENT__ELEMENT = eINSTANCE.getAVElement_Element();

  }

} //InteractiontxtPackage
