/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.interactiontxt;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see ca.udem.iro.geodes.interaction.interactiontxt.InteractiontxtPackage
 * @generated
 */
public interface InteractiontxtFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  InteractiontxtFactory eINSTANCE = ca.udem.iro.geodes.interaction.interactiontxt.impl.InteractiontxtFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>CA Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CA Element</em>'.
   * @generated
   */
  CAElement createCAElement();

  /**
   * Returns a new object of class '<em>CElement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CElement</em>'.
   * @generated
   */
  CElement createCElement();

  /**
   * Returns a new object of class '<em>AElement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AElement</em>'.
   * @generated
   */
  AElement createAElement();

  /**
   * Returns a new object of class '<em>Interaction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interaction</em>'.
   * @generated
   */
  Interaction createInteraction();

  /**
   * Returns a new object of class '<em>Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition</em>'.
   * @generated
   */
  Condition createCondition();

  /**
   * Returns a new object of class '<em>Start Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Start Transition</em>'.
   * @generated
   */
  StartTransition createStartTransition();

  /**
   * Returns a new object of class '<em>Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transition</em>'.
   * @generated
   */
  Transition createTransition();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>CI Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CI Element</em>'.
   * @generated
   */
  CIElement createCIElement();

  /**
   * Returns a new object of class '<em>CL Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CL Element</em>'.
   * @generated
   */
  CLElement createCLElement();

  /**
   * Returns a new object of class '<em>CCanvas</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CCanvas</em>'.
   * @generated
   */
  CCanvas createCCanvas();

  /**
   * Returns a new object of class '<em>CV Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CV Element</em>'.
   * @generated
   */
  CVElement createCVElement();

  /**
   * Returns a new object of class '<em>AI Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AI Element</em>'.
   * @generated
   */
  AIElement createAIElement();

  /**
   * Returns a new object of class '<em>AO Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AO Element</em>'.
   * @generated
   */
  AOElement createAOElement();

  /**
   * Returns a new object of class '<em>AL Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AL Element</em>'.
   * @generated
   */
  ALElement createALElement();

  /**
   * Returns a new object of class '<em>ACanvas</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ACanvas</em>'.
   * @generated
   */
  ACanvas createACanvas();

  /**
   * Returns a new object of class '<em>AV Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AV Element</em>'.
   * @generated
   */
  AVElement createAVElement();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  InteractiontxtPackage getInteractiontxtPackage();

} //InteractiontxtFactory
