/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.validation;

import ca.udem.iro.geodes.interaction.validation.AbstractInteractiontxtValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class InteractiontxtValidator extends AbstractInteractiontxtValidator {
}
