/*
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractInteractiontxtScopeProvider extends DelegatingScopeProvider {
}
