<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="auxiliar" nsURI="http:\\geodes.iro.ca\auxiliar" nsPrefix="auxiliar">
  <eClassifiers xsi:type="ecore:EClass" name="Controll">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//AlphaNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="desisions" upperBound="-1"
        eType="#//BetaNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokenConfigurations" upperBound="-1"
        eType="#//TokenConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalQueue" upperBound="-1"
        eType="#//QueueElem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alphaParents" upperBound="-1"
        eType="#//AlphaParent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TokenConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokenID" eType="#//QueueElem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokens" upperBound="-1"
        eType="#//Token" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDirty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfTokens" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrevValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlphaNode" eSuperTypes="#//ReteNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toBeta" upperBound="-1"
        eType="#//BetaNode" eOpposite="#//BetaNode/fromAlpha"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlphaNodeLayer" eSuperTypes="#//AlphaNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasParams" upperBound="-1"
        eType="#//AlphaNodeParam" eOpposite="#//AlphaNodeParam/inLayer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layerID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlphaNodeControll" eSuperTypes="#//AlphaNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlphaNodeParam" eSuperTypes="#//AlphaNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleParameterID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inLayer" eType="#//AlphaNodeLayer"
        eOpposite="#//AlphaNodeLayer/hasParams"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="queue" upperBound="-1"
        eType="#//QueueElem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePtr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueueElem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//StateRef" eOpposite="#//StateRef/inConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ElemRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokenConfiguration" eType="#//TokenConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dirtyStates" upperBound="-1"
        eType="#//StateRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dirtyLayers" upperBound="-1"
        eType="#//StateRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dirtyElements" upperBound="-1"
        eType="#//ElemRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElemRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inState" eType="#//StateRef"
        eOpposite="#//StateRef/hasElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemPtr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statePtr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layerPtr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasElements" upperBound="-1"
        eType="#//ElemRef" eOpposite="#//ElemRef/inState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDirty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inConfiguration" eType="#//QueueElem"
        eOpposite="#//QueueElem/states"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReteNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BetaNode" eSuperTypes="#//ReteNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTokens" upperBound="-1"
        eType="#//Token"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfTokensOld" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positiveValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromAlpha" upperBound="-1"
        eType="#//AlphaNode" eOpposite="#//AlphaNode/toBeta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlphaParent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alphas" upperBound="-1"
        eType="#//AlphaNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleParameterID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirtyState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preCond" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirtyLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="GuardSequence"/>
</ecore:EPackage>
