/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.ide;

import ca.udem.iro.geodes.interaction.ide.AbstractInteractiontxtIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class InteractiontxtIdeModule extends AbstractInteractiontxtIdeModule {
}
