/*
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction.ide


/**
 * Use this class to register ide components.
 */
class InteractiontxtIdeModule extends AbstractInteractiontxtIdeModule {
}
