/**
 * generated by Xtext 2.19.0
 */
package ca.udem.iro.geodes.interaction;

import ca.udem.iro.geodes.interaction.AbstractInteractiontxtRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class InteractiontxtRuntimeModule extends AbstractInteractiontxtRuntimeModule {
}
